//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "parking_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    pub parking_type: String,
    pub total_capacity: i16,
    pub short_capacity: i16,
    pub other_capacity: i16,
    pub updated_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::parking_stats::Entity")]
    ParkingStats,
}

impl Related<super::parking_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ParkingStats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
